package org.omg.DynamicAny;


/**
* org/omg/DynamicAny/DynSequence.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tester/jenkins/workspace/zulu8-build-macosx/zulu-src.git/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Monday, April 18, 2022 8:56:49 AM PDT
*/


/**
    * DynSequence objects support the manipulation of IDL sequences.
    */
public interface DynSequence extends DynSequenceOperations, org.omg.DynamicAny.DynAny, org.omg.CORBA.portable.IDLEntity 
{
} // interface DynSequence
