package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/LOCATION_FORWARD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tester/jenkins/workspace/zulu8-build-macosx/zulu-src.git/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Monday, April 18, 2022 8:56:49 AM PDT
*/

public interface LOCATION_FORWARD
{

  /**
     * Indicates a LocationForward reply status. One possible value for 
     * <code>RequestInfo.reply_status</code>.
     * @see RequestInfo#reply_status
     * @see SUCCESSFUL
     * @see SYSTEM_EXCEPTION
     * @see USER_EXCEPTION
     * @see TRANSPORT_RETRY
     */
  public static final short value = (short)(3);
}
